name: Building and Uploading all

on:
  workflow_dispatch:
    inputs:
      formula:
        description: Formula name
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
          - os: macos-10.15
          - os: macos-10.15
            env: { MACOSX_DEPLOYMENT_TARGET: 10.13 }
          - os: macos-11.0
    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Build bottles
        run: |
          brew test-bot --only-cleanup-before
          brew test-bot --only-formulae ${{github.event.inputs.formula}}
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: '*.bottle.*'
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Set up git
        uses: Homebrew/actions/git-user-config@master
      - name: Download bottles
        uses: actions/download-artifact@v2
        with:
          name: bottles
      - name: Publish bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
        run: brew pr-upload --debug
      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
